from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_LEFT
import io


DARK        = colors.HexColor("#0e0e0e")
ACCENT      = colors.HexColor("#c8f560")
LIGHT_TEXT  = colors.HexColor("#444444")
MID_TEXT    = colors.HexColor("#222222")


def _styles():
    base = getSampleStyleSheet()

    title = ParagraphStyle(
        "CFTitle",
        fontName="Helvetica-Bold",
        fontSize=18,
        textColor=DARK,
        spaceAfter=4,
    )
    subtitle = ParagraphStyle(
        "CFSubtitle",
        fontName="Helvetica",
        fontSize=10,
        textColor=LIGHT_TEXT,
        spaceAfter=16,
    )
    label = ParagraphStyle(
        "CFLabel",
        fontName="Helvetica-Bold",
        fontSize=8,
        textColor=colors.HexColor("#888888"),
        spaceBefore=14,
        spaceAfter=4,
        leading=10,
    )
    body = ParagraphStyle(
        "CFBody",
        fontName="Helvetica",
        fontSize=10,
        textColor=MID_TEXT,
        leading=15,
        spaceAfter=4,
    )
    recruiter = ParagraphStyle(
        "CFRecruiter",
        fontName="Helvetica",
        fontSize=10,
        textColor=colors.HexColor("#1a4a7a"),
        leading=15,
        spaceAfter=4,
    )
    return title, subtitle, label, body, recruiter


def generate_pdf(company: str, result: dict, recruiters: list) -> bytes:
    """
    Render the career fair prep output as a PDF and return raw bytes.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        leftMargin=0.85 * inch,
        rightMargin=0.85 * inch,
        topMargin=0.85 * inch,
        bottomMargin=0.85 * inch,
    )

    title_style, subtitle_style, label_style, body_style, recruiter_style = _styles()
    story = []

    # ── Header ────────────────────────────────────────────────────────────────
    story.append(Paragraph(f"Career Fair Prep", title_style))
    story.append(Paragraph(f"Company: {company}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=ACCENT, spaceAfter=10))

    def add_section(label_text, content, style=None):
        story.append(Paragraph(label_text.upper(), label_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#dddddd"), spaceAfter=6))
        s = style or body_style
        for line in content.split("\n"):
            line = line.strip()
            if line:
                story.append(Paragraph(line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"), s))
                story.append(Spacer(1, 2))
        story.append(Spacer(1, 6))

    add_section("01 · Tailored Talking Points", result.get("talking_points", ""))
    add_section("02 · Likely Recruiter Questions + Suggested Answers", result.get("recruiter_questions", ""))
    add_section("03 · Your Differentiating Angle + 30-Second Pitch", result.get("differentiating_angle", ""))

    if result.get("recruiter_tips"):
        add_section("04 · Recruiter-Specific Tips", result["recruiter_tips"], style=recruiter_style)

    # ── Personal highlights per recruiter ─────────────────────────────────────
    recruiters_with_highlights = [
        r for r in recruiters
        if r.get("personal_highlights", {}).get("tags")
    ]
    if recruiters_with_highlights:
        story.append(Paragraph("RECRUITER PERSONAL INTERESTS", label_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#dddddd"), spaceAfter=6))
        for r in recruiters_with_highlights:
            name = r.get("name", "Recruiter")
            tags = r["personal_highlights"]["tags"]
            sentences = r["personal_highlights"].get("sentences", {})
            story.append(Paragraph(f"<b>{name}</b>", body_style))
            for tag in tags:
                story.append(Paragraph(f"• {tag}", body_style))
                if tag in sentences:
                    sentence = sentences[tag].replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                    story.append(Paragraph(f"<i>\"{sentence}\"</i>",
                        ParagraphStyle("quote", fontName="Helvetica-Oblique",
                                       fontSize=9, textColor=LIGHT_TEXT, leftIndent=12, leading=13)))
            story.append(Spacer(1, 6))

    # ── Footer ────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#dddddd")))
    story.append(Paragraph(
        "Generated by Career Fair Prep Agent · Built at CMU Tepper",
        ParagraphStyle("footer", fontName="Helvetica", fontSize=8,
                       textColor=LIGHT_TEXT, spaceBefore=6)
    ))

    doc.build(story)
    return buf.getvalue()
